version: '3.9'

services:
  google-search-mongodb:
    image: mongo:6.0
    container_name: google-search-mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - google-search

  google-search-api:
    build: .
    container_name: google-search-api
    networks:
      - google-search
    ports:
      - 3000:3000
    depends_on:
      - google-search-mongodb

networks:
  google-search:
    external: true
